### ISSUE TITLE
Bot seems to be working on one server, but appears as offline in another.

### ISSUE THREAD

**Issue by changuila** [DreamExposure/DisCal-Discord-Bot#77] opened 2020-10-22 19:41 UTC
The bug is affecting one of my servers, and all its users.

I added this bot to two servers a while ago, about a week or so.

I'm using it in the Discord app for the computer, specifically Windows 10.

I'm not really sure, to be honest. I added this bot on two servers as I mentioned. It's working just fine on the first, however, the bot appears as "offline" on the other server, so there is no way of interacting with the bot.

I'm not really sure on how to fix this, I've tried changing permissions for the bot, kicking it and adding it again, tagging it directly...

**Comment by smnc** [comment] 2020-10-22 20:02
Hi changuila,
It's not a bug; the bot runs in multiple instances (called shards). One of the shards is down right now, and we'll get it back up and running as soon as possible. One of your servers is running on the crashed shard, the other is running on one of the other shards.
Nothing you can do right now, we'll get it fixed as soon as we can.

In the future, the support Discord server is the best place to first report a problem: https://discord.gg/fbysxG it's easier for us to sort and manage problems there before determining if we need to add an issue to the GitHub.

**Comment by NovaFox161** [comment] 2020-10-29 07:28
Closing as invalid

**Closed by NovaFox161** 2020-10-29 07:28 UTC
Labels: bug
