### ISSUE TITLE
Attendance reaction

### ISSUE THREAD

**Issue by Toastiiiis** [DreamExposure/DisCal-Discord-Bot#71] opened 2020-09-26 16:17 UTC
**Is your feature request related to a problem? Please describe.**
My clan members are very frustrated with having to use the rsvp commands to mark attendance.

**Describe the solution you'd like**
The bot automatically adding reactions such as:
:white_check_mark: Attending
:clock1030: Late
:x: Not Attending
:question: Uncertain

**Describe alternatives you've considered**
There is a bot that already has this feature, however it is unable to recur events reliably
![image](https://user-images.githubusercontent.com/71938364/94345129-1c62ed00-0024-11eb-925d-4a5336e9918b.png)

**Additional context**
I don't think the system proposed in this thread needs to be as complex as the one shown in the screenshot.
The bot simply adding reactions so you don't have to would be enough for the people using DisCal I believe.
For the comfort of everybody this attendance feature should be toggleable if possible.

Thank you for reading,
Toastiiiis :)

**Comment by NovaFox161** [comment] 2020-09-26 21:26
Duplicate of #52 please add as comment to that issue instead.

**Closed by NovaFox161** 2020-09-26 21:26 UTC
Labels: enhancement
